services:
  - name: CALS (Facilities)
    id: facility_search
    enabled: true
    roles: []
    privileges: 
      - ['Resource Management', 'Facility-search-rollout']
      - ['CWS Case Management System', 'Facility-search-rollout']
      - ['CWS Case Management System', 'Resource Management', 'Facility-search-rollout']
    summary: >
      Search for Facility
    href: /search
